### ISSUE TITLE
Can not pull from Docker hub

### ISSUE THREAD

**Issue by sylflo** [nagimov/agendav-docker#2]
Hi I try to pull your image using docker command but it's unsuccessful

```
 sudo docker pull nagimov/agendav-docker
Using default tag: latest
Error response from daemon: manifest for nagimov/agendav-docker:latest not found
```

**Comment by sylflo** [comment]
```
 docker pull  nagimov/agendav-docker:2.2.0
```

**Comment by nagimov** [comment]
Yes that's correct, there wasn't `:latest` tag in auto-build rules, fixed now. Both ways should work.
Just FYI, see why always using `:latest` tag is not a great idea: https://vsupalov.com/docker-latest-tag/
I just rebuilt image with `debian:stretch` base, so you might want to update.
